---
abstract: 'Config utilitites.'
author:
  - 'Michal Špaček <skim@cpan.org>'
build_requires:
  English: 0
  ExtUtils::MakeMaker: 6.36
  File::Object: 0.03
  Test::More: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Config-Utils
no_index:
  directory:
    - inc
    - t
requires:
  Error::Pure: 0.05
  Exporter: 0
  Readonly: 0
resources:
  license: http://opensource.org/licenses/bsd-license.php
  repository:
    type: git
    url: git://github.com/tupinek/Config-Utils
    web: https://github.com/tupinek/Config-Utils
version: 0.01
